const weatherConditions = {
  0: "Clear",
  1: "MainlyClear",
  2: "PartlyCloudy",
  3: "Overcast",
  45: "Fog",
  48: "DepositingRimeFog",
  51: "DrizzleLight",
  53: "DrizzleModerate",
  55: "DrizzleDense",
  56: "FreezingDrizzleLight",
  57: "FreezingDrizzleDense",
  61: "RainSlight",
  63: "RainModerate",
  65: "RainHeavy",
  66: "FreezingRainLight",
  67: "FreezingRainHeavy",
  71: "SnowFallSlight",
  73: "SnowFallModerate",
  75: "SnowFallHeavy",
  77: "SnowGrains",
  80: "RainShowersSlight",
  81: "RainShowersModerate",
  82: "RainShowersViolent",
  85: "SnowShowersSlight",
  86: "SnowShowersHeavy",
  95: "Thunderstorm",
  96: "ThunderstormWithSlightHail",
  99: "ThunderstormWithHeavyHail",
};

export default weatherConditions;
