const weatherIcons = {
  Clear: "day-sunny",
  MainlyClear: "day-sunny-overcast",
  PartlyCloudy: "day-cloudy",
  Overcast: "cloudy",
  Fog: "fog",
  DepositingRimeFog: "fog",
  DrizzleLight: "sprinkle",
  DrizzleModerate: "sprinkle",
  DrizzleDense: "sprinkle",
  FreezingDrizzleLight: "rain-mix",
  FreezingDrizzleDense: "rain-mix",
  RainSlight: "showers",
  RainModerate: "rain",
  RainHeavy: "rain",
  FreezingRainLight: "rain-mix",
  FreezingRainHeavy: "rain-mix",
  SnowFallSlight: "snow",
  SnowFallModerate: "snow",
  SnowFallHeavy: "snow",
  SnowGrains: "snowflake-cold",
  RainShowersSlight: "showers",
  RainShowersModerate: "showers",
  RainShowersViolent: "rain-wind",
  SnowShowersSlight: "snow",
  SnowShowersHeavy: "snow",
  Thunderstorm: "thunderstorm",
  ThunderstormWithSlightHail: "hail",
  ThunderstormWithHeavyHail: "hail",

  // Kondisi Khusus Berdasarkan Waktu (Siang/Malam)
  "Clear-day": "day-sunny",
  "Clear-night": "night-clear",
  "Clouds-day": "day-cloudy",
  "Clouds-night": "night-alt-cloudy",
  "Rain-day": "day-rain",
  "Rain-night": "night-alt-rain",
  "Snow-day": "day-snow",
  "Snow-night": "night-alt-snow",

  // Fallback
  Unknown: "na",
};

export default weatherIcons;
